[google_service_account]
type = "service_account"
project_id = "jovial-engine-182800"
[connections.gsheets]
spreadsheet = "1xorAPoWd81bUE2yeJN4QsEhpEoUZ5yvdGIm2h9MHbkQ"
private_key_id = "58dbbd5d01081a3ee0eba273ab2798eff35e3831"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9/TPZrADGwEyd\n6i44qUf+UZSSdgMoZIZ8Tuw3TbrztzrISTBmmrWk0CJJ+FkQ8ikZdRw+4PsgaTsd\nG2BPinxLWJ159a8lW9/mgGSKyRxeXX+6vNYkzzxoPR92Y7kIN4ZUQx7dGReZE4+B\n+KUN8JZ+rUuuYIQk6PqnBTpvBgWf1tCwnO1qen2M+8b/Bo1222qK2yt9Kl8uPdzr\nUykOg+l0xHZFQIXWWRpCO14yzy6stnl4DLMYxc91Z4tnGHCNGto9X0eBIsD3zCAA\nOfQARs+JzLoeeNxFQzqolUAJHbOAQmMUbjUltOBLpkBJhu81OOIPpY95SrUU0duT\nPmJ41tYDAgMBAAECggEAAPCTLz+dY15JIrt+o14cUo2MasBgWfShVlUSRbXB4nm6\nCzU9eDcfWzjXqpOqu8g5htGK+blQKgQLPE90hardhtvh2jFqaTNlTfUS9OgeFqNn\nbIDe8vX+ylSJvCKtzsoY2oAt02clNDx3XcEL7p/i3APhwh43w8ej5xaXXZGN4+ar\nFwo66llsCkNtVWycG9U52psHaook3OMKt0V56CKzQyjeTwm/jdrG5ilQ7iKiBe1i\npDggURhD5hN6bpgJIJBWaIb2NcIz0f+YdxvaL0nsGrqdCptkD2haqfms4h0jY8yd\nqNlxzss7IhLQecc8TTmwoIWg6gldsAoHp9pO5nDerQKBgQDxwrvQCLK6eln23Njn\noxMl1B9YcOneaAuq+zcK5Uxu0hI4Pw1dzvDZd5ZhXQI3VHH6Z5qeRtLMqkgbGvdg\n2BOdDniaosbfufeE1zxy46l2OWIMp4ON+LqoZ/IRI5tW2sAt+Dyf8tmN9SuIs9Zi\nMfmFoXX1YpXj6LXrvs0Yk/ZWHQKBgQDJLdtb1qe781UiP/gNdQPgShvCA8fiiwrk\nKqkSwOO30VFlMGeZiQ3ktOOQ8gyLgDh28++eMB/ERJK7IcXwCjbGkbflBxk30fgK\nWU6dCQzqPUqctN905Bhf+hWsGgIpXT64GVjxzVjxwHl+Y4Hk9yUnWhwKfjOFbzHl\nITSLPm2inwKBgGvcPJzA9LR7191qhJ87w1QyQlXb8otWkjYTZGhJCwO6V4SepOEA\nbbYoQ4Bm1ZFH7J4SUQpigLPtGMR3EH01ifKdPTOIgf/Y4VR0DrUXW0iyq0sIBYp2\nuRhfX8FDyI9Eg08/HBUkbOmHw4d27KPctf1nns/+zu7iqR9nfeuEP/gFAoGAIJW7\n3PE0s92i4WxJCiz01sRKIK+qFYh92B0My4vQlnph26jubtDjHjMqVNTPsVywSJwU\nKKQU0R5mQccjn1CYNKtvhLoUnJT2vv5eHFNV8y7AQgeN1goH5KvGDN0dkoOW4AzC\n+k9PY8DQLOeDJ4ncS7ZtqklsoOU0yK8LKq6O5XMCgYAi+F7srNNwJb+WQEJSCb0G\nUWa1Oe4sO0M8HRUMvhztFLrEGLNXwh44VRDcnQQFqUpcpws3nh0p6241ca761lmg\nKNin6myoHqmECDyQOaWGwBtuZ0laHdKH2P7FYMn/mqzFjPQKY+nEErlbfgTxaGn6\nplwFVSKNUhdTCAYzMtNlqA==
-----END PRIVATE KEY-----
"""
client_email = "labreagentinventary@jovial-engine-182800.iam.gserviceaccount.com"
client_id = "109791162958811973767"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/labreagentinventary%40jovial-engine-182800.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_vision]
api_key = "AIzaSyCPhrEngtBqF3-jVjfme2gGhR5XcAe9DU0"
