[google_service_account]
type = "service_account"
project_id = "jovial-engine-182800"
[connections.gsheets]
spreadsheet = "1xorAPoWd81bUE2yeJN4QsEhpEoUZ5yvdGIm2h9MHbkQ"
private_key_id = "58dbbd5d01081a3ee0eba273ab2798eff35e3831"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8YZJ3iqpQmrGo
JZtOszxKQaMqhumUyGaBcCCSL2W1OjENq7iP2UCamvYsn0CKCOhMvbeXrELLUBC4
n9NPZD524S1bJ5FswHZi4+Y5FA8947UPwX5eIueLd1pgw3W6/09RgfPE+IUxVfFa
1zlIDANUJWxnThAJJEXEBxmSpA/lNYpSKSC452V2Uv5URE1GbmGw929YT5pQ3tGF
EzCiVGnElxxEGYAFmZH2YIFtGcpPT/FKsyDJW6OLSrBvbOaLg++1QBJUhQbWECS2
yPriE9dCc/Y7resOjDPtqMWAIIS8mcOYMeKYTYoHCWjOoNznhg+uOMOmYiBPzeP4
ZPNHmN2JAgMBAAECggEAIOP+US3eR72CqEOMpsSHkcV9ChdNICOPNilQHoX1AZvb
5bGmQ0Ng0r2cnrTdbVxZxtBXBj3W2a2shbeuCs4LU/FD3Ib/jpfZ87EryKp2cM1Z
lxsnB6Obfs/DcWKfIxuhiy8f0zO6+Z6ySbSLNUeXqzDviOfpx9bT8YJ11hMcDV4q
zWksZc05FwAVNDaFuydeJGkU3yQhpIdghpbw0V7+og/GST+O6GnK+S5oRz8Hctgq
cdArOHJlimh1zaCDF1PuKmHIAn5PMHmiBOXDnmrK7oUkafOdFuKInj+e4MbTD67t
P+BqEbNc5XJmbrbX/4RrNHizQj6t+hGLDjEmRUqg8wKBgQD8jfNXBbT0uakdEb8I
gVV+8mLPqIISYWjY+0WqB7Z6cU2q658gOIuiQqeKLV0O4foq6NA5p6dmZyMIkoHM
lx/yfJ0rdplQhD6w/+XzS4gb8rRUBP2rW51UKAUq/jYBqgX+NTJkOUZgngyqaY/J
EDY1duXdSmSP31eUiA+FeGKj3wKBgQC+837T9VyX0S/MbJk/rRmpgj9a39kltE6P
YEHmTruZ3Dik7OnU6WVtbRsMfQr3GRaFT85/iDl3/0BFraNB9e8O5l976GrohITN
m3wui88TtdsnUW84t/yQ73WlqZ+FsKQPVT8OR/8sKoyucMLvnI1Ctd26iydRZgk3
1I8YcpRrlwKBgHD1DGFfrA/I+lqGFWs4bYTZ5Ff8hjCyYLKrr/zcdkFNa++GcyV2
JP3t0gF7SKPfboTCnF8tHTIv7vtmi6d18FQEaEeIRAo/G8sOqUqn/biCVSU/FjYO
Q8/gFm+kQ4N7CDMql987vr538jJGBIlpNtWy2ByhqViwC/vi3w5TScsBAoGBAIM9
8InWNlHSYTvr2Fi/rMeo0cqv2BvmFajNy/1zV9WkWvpgK0c/M4tGVjT7LLIw+B2g
gJl/E6C6O36onXEUi7598FrFn9U4X97BY1TKmwU9FOetPPiK3HjxXLcEIrRMeDZh
rPkv2t6MUC0FK7Zsr1qOjVtNkTSNIQDSg5eWCRT5AoGBAIrwqaGw7QndjbxdaSVu
UjoSorkaFrdQEYyuL8HQRIpUuYsVQJf8r4RYL7Kgnpmo3n9pQjuYsm/OvkPg1srr
IP1KntspLkC8EeUjF3RM5NGLZpPP4r11INGB8NRz4cmOOAOrHakj+uEPEVNe5cMq
7E7XiUmyT1q54DSd6mVa5IKb
-----END PRIVATE KEY-----
"""
client_email = "labreagentinventary@jovial-engine-182800.iam.gserviceaccount.com"
client_id = "109791162958811973767"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/labreagentinventary%40jovial-engine-182800.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_vision]
api_key = "AIzaSyCPhrEngtBqF3-jVjfme2gGhR5XcAe9DU0"
